# The URL, device ID and API keys are to be filled by you and is not to be shared with anyone
#For Privacy i use 'XXXXXXXXX'
#You can find SSID in your Twilio Dashboard
SSID = 'AC1xxxxxxxxxxxxxxxxxxxxxxe'
#You can find AUTH TOKEN on your Twilio Dashboard
AUTH_TOKEN = 'e206xxxxxxxxxxxxxxxxx3cf'
#FROM_NUMBER,This is the no. generated by Twilio.
FROM_NUMBER = '+1xxxxxxxxx5'
#TO_NUMBER,This is your number
TO_NUMBER = '+1xxxxxxxxx9'
MAILGUN_API_KEY = "1bcbxxxxxxxxxxxxxxxxxxxxxb4"
SANDBOX_URL = "sandboxa1xxxxxxxxxxxxxxxxxxxxxxxx.mailgun.org"
SENDER_EMAIL = "test@sandboxa1xxxxxxxxxxxxxxxxxxxxxxxd.mailgun.org"
RECIPIENT_EMAIL = "xxxxx@gmail.com"
API_KEY = "fcxxxxxxxxxx-xxxx-axxx-exxxxxxxxxxe"
DEVICE_ID = "BOLT1xxxxx4"
FRAME_SIZE = 4
MUL_FACTOR = 3

#FRAME_SIZE = 10
#MUL_FACTOR = 6
